Add friendships
elberthcorniell/ciao-social-ror pull request #2
Opened 2020-12-15 14:10 UTC by elberthcorniell

In this pull request we want to add Friendships with:
- Create friend requests.
- See your friends requests.
- See incoming requests.
- Accept requests.
- Decline requests.
- See your friends.

2020-12-15 17:05 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

Hello @elberthcorniell and @cvilla714, Great job! 👏  

You've done an awesome job so far 👌. But there are still some changes that are necessary for this project to be approved.

- [x]  User model `has_many :inverted_friendships, class_name: "Friendship", foreign_key: "friend_id"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User should be able to invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User should be able to see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User should be able to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User should be able to reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] There should be a button to invite a user to friendship on the user's list page and on the single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] Posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] Nice job on the test you have written, however, they are not running due to your naming convention, kindly take a look at this series of[ articles on RSpec](https://www.microverse.org/blog-authors/uduak-essien). 
- [x] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  
See affected files below:
> `frienships/index.html.erb
> `layouts/application.html.erb`
> `users/_friend_btn.html.erb`
**The Resources below may come in handy**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- [x] [OPTIONAL] It will be a good idea to have the name of the logged-in user display at the top to easily identify which user is logged in.
- [ ] Update your read file to reflect the authors.

####  You can take look at this article as a hint: [https://smartfunnycool.com/friendships-in-activerecord](https://smartfunnycool.com/friendships-in-activerecord/).

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-12-15 17:05 UTC, acushlakoncept commented on app/views/users/_friend_btn.html.erb
> +<% end %>
There should be NO application logic in the views nor helpers (no Post.new, Comment.create, current_user.friends.find_by(...)...). Everything connected with data processing should be encapsulated in models and used in controllers.

2020-12-15 17:05 UTC, acushlakoncept commented on app/models/user.rb
> +    Friendship.select("(CASE WHEN user_id = #{self[:id]} THEN friend_id ELSE user_id END) AS user_id, status").where(['(user_id = ? OR friend_id = ?)', self[:id], self[:id]])
Break method into multiple lines and delete `# rubocop:disable Layout/LineLength` since it's a bad practice disabling rubocop error checks.

2020-12-15 19:24 UTC, Georjane requested changes
## Status: Changes Required 🔁 🚫 
### Hi Team 🙌 
Great work so far.👍👌 You have done a nice job implementing the changes required by the previous TSE. To get this milestone approved, please make sure the following is working;🚩🚩

- [x] You have written a couple of examples for your rspec test. But I was aunable to run the test.
- [ ] Please kindly update your Readme too with instructions for testing 
- [ ] Your views still have a lot of logic insidem especially your user modelm please refer to the resources provided above by the previous TSE to better understand how to separate the logic from the view folder.

Feel free to reach out to e on slack if you have any questions, Witah Georjane👍

Good luck on your project and happy coding!!💻

2020-12-16 00:23 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****


 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2020-12-16 14:08 UTC, merged